[build]
	command = "npx pnpm install --store=node_modules/.pnpm-store && npx pnpm build"

[build.environment]
	NODE_VERSION = "16"
	NPM_FLAGS = "--version" # prevent Netlify npm install

[[redirects]]
	from = "/*"
	to = "index.html"
	status = 200
